version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/ssl/certs:/etc/nginx/certs:ro
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile.prod
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis
      - nginx
    environment:
      - VIRTUAL_HOST=api.baselaragoproject.test
      - VIRTUAL_PORT=8080
      - HTTPS_METHOD=static
    networks:
      default:
        aliases:
          - api.baselaragoproject.test
    restart: unless-stopped
    deploy:
      replicas: 2

  worker:
    build:
      context: ./api
      dockerfile: ../docker/worker/Dockerfile.prod
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis
      - elasticmq
    environment:
      - VIRTUAL_HOST=worker.baselaragoproject.test
      - VIRTUAL_PORT=8081
      - HTTPS_METHOD=static
    networks:
      default:
        aliases:
          - worker.baselaragoproject.test
    restart: unless-stopped
    deploy:
      replicas: 3  # Scale workers independently

  api-nginx:
    image: nginx:alpine
    volumes:
      - ./docker/api/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=api.baselaragoproject.test
      - VIRTUAL_PORT=8080
      - HTTPS_METHOD=static
    networks:
      default:
        aliases:
          - api.baselaragoproject.test
    restart: unless-stopped

  redis:
    image: redis:alpine
    environment:
      - VIRTUAL_HOST=redis.baselaragoproject.test
      - VIRTUAL_PORT=6379
      - HTTPS_METHOD=static
    networks:
      default:
        aliases:
          - redis.baselaragoproject.test
    restart: unless-stopped

  elasticmq:
    image: softwaremill/elasticmq
    container_name: elasticmq
    environment:
      - VIRTUAL_HOST=sqs.baselaragoproject.test
      - VIRTUAL_PORT=9325
      - HTTPS_METHOD=static
    ports:
      - "9324:9324"
    volumes:
      - ./docker/elasticmq/elasticmq.conf:/opt/elasticmq.conf
    command: ["java", "-Dconfig.file=/opt/elasticmq.conf", "-jar", "/opt/elasticmq-server.jar"]
    networks:
      default:
        aliases:
          - sqs.baselaragoproject.test
    restart: unless-stopped

  db:
    image: mysql
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "3309:3306"
    expose:
      - 3306
    volumes:
      - ./my-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=D3vB4s3L4r4G0!
      - MYSQL_DATABASE=dev_base_lara_go
      - MYSQL_USER=api_user
      - MYSQL_PASSWORD=b4s3L4r4G0212!

volumes:
  my-db:
    driver: local 